#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

fail() {
  printf '%s\n' "v1 contract verification failure: $*" >&2
  exit 1
}

require_file() {
  path=$1
  [ -f "$ROOT/$path" ] || fail "required file is missing: $path"
}

require_text() {
  path=$1
  text=$2
  grep -F -- "$text" "$ROOT/$path" >/dev/null ||
    fail "required contract text is missing from $path: $text"
}

require_function_text() {
  path=$1
  function_name=$2
  text=$3
  awk -v function_name="$function_name" '
    index($0, function_name "(") { in_function = 1 }
    in_function { print }
    in_function && /^}/ { exit }
  ' "$ROOT/$path" | grep -F -- "$text" >/dev/null ||
    fail "required contract text is missing from $path function $function_name: $text"
}

CONTRACT=docs/r0lab-v1-contract.md
VERIFICATION=docs/r0lab-v1-verification.md
SHADOW_PLAN=docs/shadow-page-transition-plan.md
RAW_PLAN=docs/wxshadow-raw-pte-implementation-plan.md
REPLICA_PLAN=docs/wxshadow-replica-plan.md
RAW_COMPAT=docs/pixel7-panther-raw-pte-compatibility.md
S4_PLAN=docs/wxshadow-s4-brk-step-plan.md
FINAL_ROADMAP=docs/wxshadow-final-experiment-roadmap.md
F2_PLAN=docs/wxshadow-f2-two-page-lab-harness-plan.md
F3_PLAN=docs/wxshadow-f3-page-local-patch-records-plan.md
F4_PLAN=docs/wxshadow-f4-hook-routing-by-page-record-plan.md
F42_POSITIVE_PLAN=docs/wxshadow-f4.2-positive-trigger-plan.md
F43_GUP_PLAN=docs/wxshadow-f4.3-gup-hook-routing-plan.md
F44_FORK_PLAN=docs/wxshadow-f4.4-fork-hook-routing-plan.md
F45_SYSCALL_PRCTL_PLAN=docs/wxshadow-f4.5-syscall-prctl-routing-plan.md
F45_PRCTL_CHECKPOINT=docs/wxshadow-f4.5-prctl-routing-source-checkpoint.md
F46_EXIT_PLAN=docs/wxshadow-f4.6-exit-hook-routing-plan.md
DEVELOPMENT_SEQUENCE=docs/wxshadow-development-sequence.md

require_file "$CONTRACT"
require_file "$VERIFICATION"
require_file "$SHADOW_PLAN"
require_file "$RAW_PLAN"
require_file "$REPLICA_PLAN"
require_file "$RAW_COMPAT"
require_file "$S4_PLAN"
require_file "$FINAL_ROADMAP"
require_file "$F2_PLAN"
require_file "$F3_PLAN"
require_file "$F4_PLAN"
require_file "$F42_POSITIVE_PLAN"
require_file "$F43_GUP_PLAN"
require_file "$F44_FORK_PLAN"
require_file "$F45_SYSCALL_PRCTL_PLAN"
require_file "$F45_PRCTL_CHECKPOINT"
require_file "$F46_EXIT_PLAN"
require_file "$DEVELOPMENT_SEQUENCE"
require_file docs/kpm-research-plan.md
require_file docs/kpm-compatibility-matrix.md

require_text "$CONTRACT" 'r0lab v1 Implementation Contract'
require_text "$CONTRACT" 'target_id'
require_text "$CONTRACT" 'workers_shutdown=1'
require_text "$CONTRACT" 'S1: Contract And Regression Gate'
require_text "$CONTRACT" 'S4: BRK/Single-Step ABI Gate'
require_text "$CONTRACT" 'wxshadow-s4-brk-step-plan.md'
require_text "$SHADOW_PLAN" 'UXN-Gated Shadow Page Transition Plan'
require_text "$SHADOW_PLAN" 'result=blocked'
require_text "$SHADOW_PLAN" 'user_xom_read_fault=absent'
require_text "$SHADOW_PLAN" 'boot_reason=kernel_panic'
require_text "$SHADOW_PLAN" 'visible-clone'
require_text "$RAW_PLAN" 'same VA, two PFNs'
require_text "$RAW_PLAN" 'record_backend=raw_two_pfn'
require_text "$REPLICA_PLAN" 'wxshadow Replica Plan For r0lab'
require_text "$REPLICA_PLAN" 'no `shadow_xom` symbols in KPM source'
require_text "$REPLICA_PLAN" 'Future work must'
require_text "$REPLICA_PLAN" 'struct r0lab_page_record'
require_text "$REPLICA_PLAN" 'record_backend=visible_clone'
require_text "$FINAL_ROADMAP" 'wxshadow Final Experiment Roadmap'
require_text "$FINAL_ROADMAP" 'Raw Page Table Skeleton'
require_text "$FINAL_ROADMAP" 'Two-Page Lab Harness'
require_text "$FINAL_ROADMAP" 'Page-Local Patch Records'
require_text "$FINAL_ROADMAP" 'Hook Routing By Page Record'
require_text "$FINAL_ROADMAP" 'Controlled Hidden-Read Decision Gate'
require_text "$FINAL_ROADMAP" 'Do not re-enable `shadow_xom`'
require_text "$FINAL_ROADMAP" 'Do not add arbitrary process or arbitrary address support.'
require_text "$FINAL_ROADMAP" 'raw_page_table_slots'
require_text "$FINAL_ROADMAP" 'Slot 1 is intentionally inert until F2'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f2-two-page-lab-harness-plan.md'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f3-page-local-patch-records-plan.md'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f4-hook-routing-by-page-record-plan.md'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f4.2-positive-trigger-plan.md'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f4.3-gup-hook-routing-plan.md'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f4.4-fork-hook-routing-plan.md'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-development-sequence.md'
require_text "$FINAL_ROADMAP" 'Plan checkpoints are docs/contract only.'
require_text "$FINAL_ROADMAP" 'No hook-family migration starts unless'
require_text "$FINAL_ROADMAP" 'scripts/test_raw_exit_hook_device.sh'
require_text "$FINAL_ROADMAP" 'scripts/test_raw_hook_routing_device.sh'
require_text "$FINAL_ROADMAP" 'Completed F4.4 gate'
require_text "$FINAL_ROADMAP" 'build/evidence/raw-fork-hook-routing-20260724-031442.log'
require_text "$FINAL_ROADMAP" 'status_source=cross_clear'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f4.5-syscall-prctl-routing-plan.md'
require_text "$FINAL_ROADMAP" 'docs/wxshadow-f4.6-exit-hook-routing-plan.md'
require_text "$FINAL_ROADMAP" 'scripts/test_raw_fork_hook_routing_device.sh'
require_text "$DEVELOPMENT_SEQUENCE" 'wxshadow Planned Development Sequence'
require_text "$DEVELOPMENT_SEQUENCE" 'This document turns the roadmap into a fixed development queue.'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.1: Abort Hook Routing'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.2: Fault Hook Routing'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.3: GUP Hook Routing'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.4: Fork Hook Routing'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.5: Syscall And Prctl Routing'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.6: Exit Hook Routing'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.7: F4 Integration Gate'
require_text "$DEVELOPMENT_SEQUENCE" 'Planning Gate'
require_text "$DEVELOPMENT_SEQUENCE" 'Only one source slice may be active at a time.'
require_text "$DEVELOPMENT_SEQUENCE" 'scripts/test_raw_hook_routing_device.sh'
require_text "$DEVELOPMENT_SEQUENCE" 'scripts/test_raw_fault_hook_routing_device.sh'
require_text "$DEVELOPMENT_SEQUENCE" 'scripts/test_raw_fault_hook_positive_preflight_device.sh'
require_text "$DEVELOPMENT_SEQUENCE" 'docs/wxshadow-f4.2-positive-trigger-plan.md'
require_text "$DEVELOPMENT_SEQUENCE" 'docs/wxshadow-f4.3-gup-hook-routing-plan.md'
require_text "$DEVELOPMENT_SEQUENCE" 'docs/wxshadow-f4.4-fork-hook-routing-plan.md'
require_text "$DEVELOPMENT_SEQUENCE" 'docs/wxshadow-f4.5-syscall-prctl-routing-plan.md'
require_text "$DEVELOPMENT_SEQUENCE" 'docs/wxshadow-f4.6-exit-hook-routing-plan.md'
require_text "$DEVELOPMENT_SEQUENCE" 'F4.2a verification ladder'
require_text "$DEVELOPMENT_SEQUENCE" 'scripts/test_raw_gup_hook_routing_device.sh'
require_text "$DEVELOPMENT_SEQUENCE" 'scripts/test_raw_fork_hook_device.sh'
require_text "$DEVELOPMENT_SEQUENCE" 'scripts/test_raw_fork_hook_routing_device.sh'
require_text "$DEVELOPMENT_SEQUENCE" 'file-backed RX plus shadow-PTE access-flag clear'
require_text "$DEVELOPMENT_SEQUENCE" 'If a failed positive smoke exposes a new development gap, classify it'
require_text "$DEVELOPMENT_SEQUENCE" 'Do not pull these behaviors into F4 source checkpoints.'
require_text "$DEVELOPMENT_SEQUENCE" 'Development Control Loop'
require_text "$DEVELOPMENT_SEQUENCE" 'D1 source scaffold has static/build evidence.'
require_text "$DEVELOPMENT_SEQUENCE" 'build/evidence/raw-fork-hook-20260724-031422.log'
require_text "$DEVELOPMENT_SEQUENCE" 'build/evidence/raw-fork-hook-routing-20260724-031442.log'
require_text "$DEVELOPMENT_SEQUENCE" 'The next source checkpoint is'
require_text "$DEVELOPMENT_SEQUENCE" 'D0 plan gate is complete.'
require_text "$DEVELOPMENT_SEQUENCE" 'D1-D3 syscall/getpid read-cycle routing is implemented and gate-passed'
require_text "$DEVELOPMENT_SEQUENCE" 'D4-D6 Lab-private prctl dispatch/patch routing is implemented and'
require_text "$DEVELOPMENT_SEQUENCE" 'build/evidence/raw-prctl-hook-routing-20260724-035944.log'
require_text "$DEVELOPMENT_SEQUENCE" 'build/evidence/raw-syscall-hook-routing-20260724-033233.log'
require_text "$F2_PLAN" 'raw slot arm <token> <slot> <page>'
require_text "$F2_PLAN" 'raw page table run <token>'
require_text "$F2_PLAN" 'scripts/test_raw_page_table_device.sh'
require_text "$F3_PLAN" 'wxshadow F3 Page-Local Patch Records Plan'
require_text "$F3_PLAN" 'Status: implemented'
require_text "$F3_PLAN" 'plan-only checkpoint'
require_text "$F3_PLAN" 'raw slot patch byte <token> <slot> <generation> <offset> <value>'
require_text "$F3_PLAN" 'raw slot patch word <token> <slot> <generation> <offset> <word>'
require_text "$F3_PLAN" 'raw slot patch release <token> <slot> <generation> <offset>'
require_text "$F3_PLAN" 'raw slot patch status <token> <slot>'
require_text "$F3_PLAN" 'patch_capacity=1024'
require_text "$F3_PLAN" 'raw page table patch records run <token>'
require_text "$F3_PLAN" 'scripts/test_raw_page_table_patch_records_device.sh'
require_text "$F3_PLAN" 'slot0_patch_record_slots=1024'
require_text "$F3_PLAN" 'slot1_after_slot0_capacity_value=88'
require_text "$F3_PLAN" 'scripts/test_raw_prctl_patch_records_device.sh'
require_text "$F3_PLAN" 'scripts/test_raw_page_table_device.sh'
require_text "$F3_PLAN" 'build/evidence/raw-page-table-patch-records-20260724-003931.log'
require_text "$F4_PLAN" 'wxshadow F4 Hook Routing By Page Record Plan'
require_text "$F4_PLAN" 'Status: F4.1 abort-routing checkpoint implemented and targeted gate-passed.'
require_text "$F4_PLAN" 'allowed files: this document'
require_text "$F4_PLAN" 'disallowed files: `kpm/r0lab.c`, `kpm/r0lab_raw_compat.c`'
require_text "$F4_PLAN" 'target mm plus page VA lookup'
require_text "$F4_PLAN" 'Current source-helper checkpoint:'
require_text "$F4_PLAN" 'Current F4.1 abort-routing checkpoint:'
require_text "$F4_PLAN" 'Active F4.2 fault-routing preflight:'
require_text "$F4_PLAN" 'docs/wxshadow-f4.2-positive-trigger-plan.md'
require_text "$F4_PLAN" 'fault-hook hits and final `42/42` behavior'
require_text "$F4_PLAN" 'reject RWX write as a trigger'
require_text "$F4_PLAN" 'file-backed RX plus shadow-PTE access-flag clear'
require_text "$F4_PLAN" 'r0lab_raw_page_find_by_mm_addr_locked'
require_text "$F4_PLAN" 'r0lab_raw_page_find_by_fault_locked'
require_text "$F4_PLAN" 'r0lab_raw_page_find_for_hook_locked'
require_text "$F4_PLAN" 'struct r0lab_raw_hook_page_token'
require_text "$F4_PLAN" 'raw hook route status <token> <slot>'
require_text "$F4_PLAN" 'hook callbacks must not free page memory'
require_text "$F4_PLAN" 'do_mem_abort'
require_text "$F4_PLAN" 'handle_mm_fault'
require_text "$F4_PLAN" 'follow_page_pte'
require_text "$F4_PLAN" 'follow_page_mask'
require_text "$F4_PLAN" 'dup_mmap'
require_text "$F4_PLAN" 'exit_mmap'
require_text "$F4_PLAN" '__arm64_sys_getpid'
require_text "$F4_PLAN" '__arm64_sys_prctl'
require_text "$F4_PLAN" 'raw_hook_route_status slot=<slot>'
require_text "$F4_PLAN" 'page_record_routed=1'
require_text "$F4_PLAN" 'scripts/test_raw_hook_routing_device.sh'
require_text "$F4_PLAN" 'arbitrary process, arbitrary `mm`, or arbitrary address support'
require_text "$F4_PLAN" 'raw-XOM, permission-fault hidden-read experiments, or `PTE_USER` changes'
require_text "$F42_POSITIVE_PLAN" 'wxshadow F4.2 Positive Trigger Plan'
require_text "$F42_POSITIVE_PLAN" 'Status: F4.2a source-checkpoint execution gate; Pixel 7 device outcome is'
require_text "$F42_POSITIVE_PLAN" 'F4.2a device outcome:'
require_text "$F42_POSITIVE_PLAN" 'build/evidence/raw-fault-hook-positive-preflight-20260724-020034.log'
require_text "$F42_POSITIVE_PLAN" 'Fixed development ladder'
require_text "$F42_POSITIVE_PLAN" 'F4.2a-D0 plan lock'
require_text "$F42_POSITIVE_PLAN" 'F4.2a-D1 source scaffold'
require_text "$F42_POSITIVE_PLAN" 'F4.2a-D2 negative regression'
require_text "$F42_POSITIVE_PLAN" 'F4.2a-D3 positive preflight'
require_text "$F42_POSITIVE_PLAN" 'F4.2a-D4 promotion or block'
require_text "$F42_POSITIVE_PLAN" 'PROT_NONE` raw-page read is blocked before `handle_mm_fault`'
require_text "$F42_POSITIVE_PLAN" 'File-backed RX shadow PTE access-flag clear'
require_text "$F42_POSITIVE_PLAN" 'First positive candidate.'
require_text "$F42_POSITIVE_PLAN" 'raw_fault_hook_positive_preflight=pass'
require_text "$F42_POSITIVE_PLAN" 'positive_route=1'
require_text "$F42_POSITIVE_PLAN" 'op=33 result=0'
require_text "$F42_POSITIVE_PLAN" 'handler_faults=0'
require_text "$F42_POSITIVE_PLAN" 'normal=42/42`, `shadow=99/99`, and final cleanup returns `42/42`'
require_text "$F42_POSITIVE_PLAN" 'RWX write trigger strings do not appear in the positive script or static'
require_text "$F42_POSITIVE_PLAN" 'If file-backed executable mapping cannot be created safely in the Lab App'
require_text "$F42_POSITIVE_PLAN" 'handle_mm_fault_positive_blocked'
require_text "$F42_POSITIVE_PLAN" 'Failure Classification'
require_text "$F42_POSITIVE_PLAN" 'Do not patch from a failed smoke directly.'
require_text "$F43_GUP_PLAN" 'wxshadow F4.3 GUP Hook Routing Plan'
require_text "$F43_GUP_PLAN" 'D2/D3 device-gate passed'
require_text "$F43_GUP_PLAN" 'build/evidence/raw-gup-hook-20260724-024012.log'
require_text "$F43_GUP_PLAN" 'build/evidence/raw-gup-hook-routing-20260724-024036.log'
require_text "$F43_GUP_PLAN" 'build/evidence/raw-hook-routing-20260724-024107.log'
require_text "$F43_GUP_PLAN" 'If a test exposes a missing behavior, do not patch source first.'
require_text "$F43_GUP_PLAN" 'D2 Recovery Protocol'
require_text "$F43_GUP_PLAN" 'D3 Evidence Protocol'
require_text "$F43_GUP_PLAN" "after slot 0's external read, slot 1 inspect still shows zero GUP hook"
require_text "$F43_GUP_PLAN" 'Fixed Development Ladder'
require_text "$F43_GUP_PLAN" 'F4.3-D0 plan lock'
require_text "$F43_GUP_PLAN" 'F4.3-D1 source scaffold'
require_text "$F43_GUP_PLAN" 'F4.3-D2 slot-0 regression'
require_text "$F43_GUP_PLAN" 'F4.3-D3 two-slot routing'
require_text "$F43_GUP_PLAN" 'F4.3-D4 commit/tag'
require_text "$F43_GUP_PLAN" 'GUP before hook resolves the page by `vma->vm_mm` plus GUP address.'
require_text "$F43_GUP_PLAN" 'The before hook stores slot and generation in `hook_local_t`.'
require_text "$F43_GUP_PLAN" 'Legacy `raw gup hook arm/status/clear <token>` remains slot-0 compatible.'
require_text "$F43_GUP_PLAN" 'scripts/test_raw_gup_hook_routing_device.sh'
require_text "$F43_GUP_PLAN" 'Wrong-page routing'
require_text "$F44_FORK_PLAN" 'wxshadow F4.4 Fork Hook Routing Plan'
require_text "$F44_FORK_PLAN" 'Status: implemented on the pinned Pixel 7.'
require_text "$F44_FORK_PLAN" 'Outcome Evidence'
require_text "$F44_FORK_PLAN" 'build/evidence/raw-fork-hook-routing-20260724-031442.log'
require_text "$F44_FORK_PLAN" 'status_source=cross_clear'
require_text "$F44_FORK_PLAN" 'shadow_pause_parent_pages(mm)'
require_text "$F44_FORK_PLAN" 'shadow_resume_parent_pages(mm)'
require_text "$F44_FORK_PLAN" 'Fixed Development Ladder'
require_text "$F44_FORK_PLAN" 'F4.4-D1 Work Packet'
require_text "$F44_FORK_PLAN" 'Allowed files:'
require_text "$F44_FORK_PLAN" 'Disallowed files:'
require_text "$F44_FORK_PLAN" 'New `raw slot fork hook arm/status/clear <token> <slot>` commands are'
require_text "$F44_FORK_PLAN" 'F4.4-D0 plan lock'
require_text "$F44_FORK_PLAN" 'F4.4-D1 source scaffold'
require_text "$F44_FORK_PLAN" 'F4.4-D2 slot-0 regression'
require_text "$F44_FORK_PLAN" 'F4.4-D3 two-slot fork routing'
require_text "$F44_FORK_PLAN" 'F4.4-D4 commit/tag'
require_text "$F44_FORK_PLAN" 'The before hook stores a bounded paused-slot set plus slot generations in'
require_text "$F44_FORK_PLAN" 'Legacy `raw fork hook arm/status/clear <token>` remains slot-0 compatible.'
require_text "$F44_FORK_PLAN" 'scripts/test_raw_fork_hook_routing_device.sh'
require_text "$F44_FORK_PLAN" 'F4.4-D2 Regression Triage Plan'
require_text "$F44_FORK_PLAN" 'raw slot fork hook status <token> 0'
require_text "$F44_FORK_PLAN" 'Do not change `dup_mmap` callbacks for this case.'
require_text "$F44_FORK_PLAN" 'Partial pause mismatch'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'wxshadow F4.5 Syscall And Prctl Routing Plan'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'Status: D1-D3 syscall routing and D4-D6 prctl routing are implemented'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'build/evidence/raw-prctl-hook-routing-20260724-035944.log'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D0 plan lock'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D1 syscall source scaffold'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D2 syscall slot-0 regression'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D3 syscall two-slot routing'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D4 prctl source scaffold'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D5 prctl slot-0 regression'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D6 prctl two-slot routing'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'F4.5-D7 commit/tag'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'docs/wxshadow-f4.5-prctl-routing-source-checkpoint.md'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'Legacy `raw syscall ... <token>` and `raw prctl ... <token>` commands remain'
require_text "$F45_SYSCALL_PRCTL_PLAN" '<token> <slot> <generation>'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'raw slot syscall read cycle hook select <token> <slot> <generation>'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'routes through selected slot plus generation'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'route through `current_mm + address` or `current_mm + request.address`'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'Patch-record capacity remains `1024` per page record.'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'scripts/test_raw_syscall_read_cycle_device.sh'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'scripts/test_raw_syscall_hook_routing_device.sh'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'scripts/test_raw_prctl_patch_records_device.sh'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'scripts/test_raw_prctl_hook_routing_device.sh'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'Stale generation accepted'
require_text "$F45_SYSCALL_PRCTL_PLAN" 'build/evidence/raw-syscall-hook-routing-20260724-033233.log'
require_text "$F45_PRCTL_CHECKPOINT" 'wxshadow F4.5 D4-D6 Prctl Routing Source Checkpoint'
require_text "$F45_PRCTL_CHECKPOINT" 'Status: D4-D6 implemented and gate-passed on Pixel 7'
require_text "$F45_PRCTL_CHECKPOINT" 'D4-D7 Execution Contract'
require_text "$F45_PRCTL_CHECKPOINT" 'No development step is allowed to discover a new scope hole'
require_text "$F45_PRCTL_CHECKPOINT" 'r0lab_raw_prctl_before()'
require_text "$F45_PRCTL_CHECKPOINT" 'r0lab_raw_prctl_hook_users_locked()'
require_text "$F45_PRCTL_CHECKPOINT" 'raw slot prctl hook arm <token> <slot> <generation>'
require_text "$F45_PRCTL_CHECKPOINT" 'raw slot prctl hook select <token> <slot> <generation>'
require_text "$F45_PRCTL_CHECKPOINT" 'raw slot prctl hook status <token> <slot>'
require_text "$F45_PRCTL_CHECKPOINT" 'raw slot prctl hook clear <token> <slot> <generation>'
require_text "$F45_PRCTL_CHECKPOINT" 'event-ring truncation fix'
require_text "$F45_PRCTL_CHECKPOINT" 'build/evidence/raw-prctl-hook-routing-20260724-035944.log'
require_text "$F45_PRCTL_CHECKPOINT" 'build/evidence/raw-prctl-read-cycle-20260724-040015.log'
require_text "$F45_PRCTL_CHECKPOINT" 'build/evidence/raw-prctl-patch-records-20260724-040036.log'
require_text "$F45_PRCTL_CHECKPOINT" 'build/evidence/raw-syscall-hook-routing-20260724-040056.log'
require_text "$F45_PRCTL_CHECKPOINT" 'R0LAB_PRCTL_OP_READ_CYCLE` has no address argument'
require_text "$F45_PRCTL_CHECKPOINT" 'route by `current_mm + address`'
require_text "$F45_PRCTL_CHECKPOINT" 'route by `current_mm + request.address`'
require_text "$F45_PRCTL_CHECKPOINT" 'r0lab_raw_hook_page_token_acquire_locked()'
require_text "$F45_PRCTL_CHECKPOINT" 'R0LAB_RAW_HOOK_PRCTL'
require_text "$F45_PRCTL_CHECKPOINT" 'raw_slot_prctl_hook_ready slot=%u generation=%llu symbol=prctl installed=1 selected=1 page_record_routed=1'
require_text "$F45_PRCTL_CHECKPOINT" 'raw mode=prctl-routing failures=0 trigger=prctl_magic route=selected_slot,address page_record_routed=1'
require_text "$F45_PRCTL_CHECKPOINT" 'scripts/test_raw_prctl_hook_routing_device.sh'
require_text "$F46_EXIT_PLAN" 'wxshadow F4.6 Exit Hook Routing Plan'
require_text "$F46_EXIT_PLAN" 'Status: plan checkpoint. Source implementation is not started.'
require_text "$F46_EXIT_PLAN" 'hook callbacks may mark and record matching page records,'
require_text "$F46_EXIT_PLAN" 'but they must not directly free page memory'
require_text "$F46_EXIT_PLAN" 'F4.6-D0 plan lock'
require_text "$F46_EXIT_PLAN" 'F4.6-D1 KPM source scaffold'
require_text "$F46_EXIT_PLAN" 'F4.6-D2 slot-0 regression'
require_text "$F46_EXIT_PLAN" 'F4.6-D3 Lab two-slot hold source'
require_text "$F46_EXIT_PLAN" 'F4.6-D4 two-slot owner-exit smoke'
require_text "$F46_EXIT_PLAN" 'F4.6-D5 lifecycle regression'
require_text "$F46_EXIT_PLAN" 'F4.6-D6 commit/tag'
require_text "$F46_EXIT_PLAN" 'raw slot exit hook arm <token> <slot> <generation>'
require_text "$F46_EXIT_PLAN" 'raw slot exit hook status <token> <slot>'
require_text "$F46_EXIT_PLAN" 'raw slot exit hook clear <token> <slot> <generation>'
require_text "$F46_EXIT_PLAN" 'raw exit hook routing hold <token>'
require_text "$F46_EXIT_PLAN" 'scripts/test_raw_exit_hook_routing_device.sh'
require_text "$F46_EXIT_PLAN" 'target_mm_scoped=1 page_record_routed=1 observe_only=0 cleanup=monitor'
require_text "$F46_EXIT_PLAN" 'verify at least two `op=34 result=0` exit-mmap hit events'
require_text "$F46_EXIT_PLAN" 'Singleton residue'
require_text kpm/r0lab.c 'enum r0lab_raw_hook_kind'
require_text kpm/r0lab.c 'enum r0lab_raw_hook_route_flags'
require_text kpm/r0lab.c 'R0LAB_RAW_HOOK_ROUTE_MUTATING'
require_text kpm/r0lab.c 'R0LAB_RAW_HOOK_ROUTE_REQUIRE_SHADOW_RX'
require_text kpm/r0lab.c 'struct r0lab_raw_hook_route_stats'
require_text kpm/r0lab.c 'struct r0lab_raw_hook_page_token'
require_text kpm/r0lab.c 'hook_route_stats'
require_text kpm/r0lab.c 'hook_route_miss_stats'
require_text kpm/r0lab.c 'r0lab_raw_page_find_by_mm_addr_locked'
require_text kpm/r0lab.c 'r0lab_raw_page_find_by_fault_locked'
require_text kpm/r0lab.c 'r0lab_raw_page_find_for_hook_locked'
require_text kpm/r0lab.c 'r0lab_raw_hook_page_token_acquire_locked'
require_text kpm/r0lab.c 'r0lab_raw_hook_page_token_release_locked'
require_text kpm/r0lab.c 'r0lab_raw_fault_hook_users_locked'
require_text kpm/r0lab.c 'R0LAB_RAW_HOOK_FAULT, vma_mm, address'
require_text kpm/r0lab.c 'raw_hook_route_status slot=%u generation=%llu hook=all'
require_text kpm/r0lab.c 'route_helper_ready=1 page_record_routed=0'
require_text kpm/r0lab.c 'table_route_outside_page=%u'
require_text kpm/r0lab.c 'migration=callbacks_slot0_compat'
require_text kpm/r0lab.c 'raw hook route status '
require_text "$FINAL_ROADMAP" 'Current status: implemented and gate-passed on Pixel 7'
require_text "$VERIFICATION" 'current 29-phase ordered acceptance run passed'
require_text "$FINAL_ROADMAP" 'Current status: F4.1 abort routing, F4.3 GUP routing, F4.4 fork routing, and'
require_text "$FINAL_ROADMAP" 'diagnostic/observe-only on this Pixel 7'
require_text "$FINAL_ROADMAP" 'handle_mm_fault_positive_blocked'
require_text "$FINAL_ROADMAP" 'F4.6 exit hook routing is the next source checkpoint'
require_text "$FINAL_ROADMAP" 'F4.5 syscall gate outcome'
require_text "$FINAL_ROADMAP" 'build/evidence/raw-syscall-hook-routing-20260724-033233.log'
require_text "$FINAL_ROADMAP" 'The active source checkpoint is F4.2a preflight, not callback migration.'
require_text "$FINAL_ROADMAP" 'The checkpoint follows the D0-D4 ladder'
require_text "$FINAL_ROADMAP" 'file-backed RX plus shadow-PTE access-flag clear'
require_text "$FINAL_ROADMAP" 'wxshadow-v2-f4-fork-routing-plan-20260724'
require_text "$FINAL_ROADMAP" 'update the plan or queue before changing source'
require_text "$VERIFICATION" 'F4 currently has the route-helper substrate and the first abort-routing slice.'
require_text "$VERIFICATION" 'docs/wxshadow-f4-hook-routing-by-page-record-plan.md'
require_text "$VERIFICATION" 'raw hook route status <token> <slot>'
require_text docs/kpm-compatibility-matrix.md 'Two-slot page-local patch records'
require_text "$VERIFICATION" 'raw_page_table_slots'
require_text docs/kpm-compatibility-matrix.md 'Raw page-table skeleton'
require_text "$CONTRACT" 'page_records'
require_text "$RAW_COMPAT" 'lab_two_pfn_pass'
require_text "$RAW_COMPAT" 'kpm_locked_target_mm_writer=proven'
require_text "$VERIFICATION" 'scripts/test_v1_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_page_table_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_read_cycle_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_syscall_read_cycle_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_prctl_patch_records_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_abort_probe_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_abort_read_cycle_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_abort_write_probe_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_abort_write_release_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_hook_routing_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_fault_hook_routing_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_fault_hook_positive_preflight_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_gup_hook_routing_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_fork_hook_routing_device.sh'
require_text "$VERIFICATION" 'docs/wxshadow-f4.3-gup-hook-routing-plan.md'
require_text "$VERIFICATION" 'docs/wxshadow-f4.4-fork-hook-routing-plan.md'
require_text "$VERIFICATION" 'two `op=31` begin events and two `op=32` finish'
require_text "$VERIFICATION" 'scripts/test_s4_raw_reg_device.sh'
require_text "$VERIFICATION" 'scripts/test_raw_exit_hook_device.sh'
require_text "$VERIFICATION" 'scripts/probe_s4_abi_device.sh'
require_text "$VERIFICATION" 'M0_LOOPS=100'
require_text "$VERIFICATION" 'm4_ready'
require_text "$VERIFICATION" 'record_backend=visible_clone'
require_text "$VERIFICATION" 'M5 target-exit lifecycle test for M3, M4, raw two-PFN, S4 BRK-only, and S4 raw-step hold states.'
require_text "$REPLICA_PLAN" 's4 abi'
require_text "$REPLICA_PLAN" 'probe-only'
require_text "$S4_PLAN" 'wxshadow S4 BRK/Single-Step Plan'
require_text "$S4_PLAN" 'BRK-only slice'
require_text "$S4_PLAN" 'must not set'
require_text "$S4_PLAN" 'skip_origin'
require_text "$S4_PLAN" 'arbitrary address breakpoints'
require_text "$S4_PLAN" 'arbitrary register/value mutation API'
require_text "$S4_PLAN" 'S4_BRK_OBSERVED'
require_text docs/kpm-research-plan.md 'M0-M5 plus raw two-PFN are complete for this pinned device and Lab App.'
require_text docs/kpm-compatibility-matrix.md 'Trusting `.kpm.exit` to block FolkPatch unload'

SCRIPTS='
scripts/build_kpm.sh
scripts/build_lab_app.sh
scripts/test_m0_environment_device.sh
scripts/test_m0_device.sh
scripts/test_m1_isolation_device.sh
scripts/test_m2_device.sh
scripts/test_m3_device.sh
scripts/test_m4_device.sh
scripts/test_m5_exit_probe_device.sh
scripts/test_m5_lifecycle_device.sh
scripts/test_m5_faults_device.sh
scripts/probe_shadow_page_capabilities_device.sh
scripts/probe_raw_pte_compat_device.sh
scripts/probe_raw_xom_device.sh
scripts/probe_s4_abi_device.sh
scripts/test_s4_brk_device.sh
scripts/test_s4_step_device.sh
scripts/test_s4_raw_step_device.sh
scripts/test_s4_raw_reg_device.sh
scripts/test_raw_device.sh
scripts/test_raw_page_table_device.sh
scripts/test_raw_page_table_patch_records_device.sh
scripts/test_raw_read_cycle_device.sh
scripts/test_raw_syscall_read_cycle_device.sh
scripts/test_raw_syscall_hook_routing_device.sh
scripts/test_raw_prctl_read_cycle_device.sh
scripts/test_raw_prctl_patch_records_device.sh
scripts/test_raw_prctl_hook_routing_device.sh
scripts/test_raw_gup_hide_device.sh
scripts/test_raw_gup_hook_device.sh
scripts/test_raw_gup_hook_routing_device.sh
scripts/test_raw_fork_hook_device.sh
scripts/test_raw_fork_hook_routing_device.sh
scripts/test_raw_fault_hook_device.sh
scripts/test_raw_fault_hook_routing_device.sh
scripts/test_raw_fault_hook_positive_preflight_device.sh
scripts/test_raw_fault_data_probe_device.sh
scripts/test_raw_hook_routing_device.sh
scripts/test_raw_abort_probe_device.sh
scripts/test_raw_abort_write_probe_device.sh
scripts/test_raw_abort_write_release_device.sh
scripts/test_raw_exit_hook_device.sh
scripts/test_v1_device.sh
'

for script in $SCRIPTS; do
  require_file "$script"
  [ -x "$ROOT/$script" ] || fail "required script is not executable: $script"
  sh -n "$ROOT/$script" || fail "shell syntax is invalid: $script"
done

if grep -E 'pgtable_entry|flush_tlb_all|vmalle1is|[[:space:]]tlbi[[:space:]]' \
  "$ROOT/kpm/r0lab.c" \
  "$ROOT/kpm/r0lab_raw_compat.c" \
  "$ROOT/kpm/r0lab_raw.h" >/dev/null; then
  fail 'r0lab KPM contains a forbidden raw page-table or global-TLB primitive'
fi

if grep -E 'shadow_xom|SHADOW_XOM|xom_mode|activate_shadow_xom' \
  "$ROOT/kpm/r0lab.c" \
  "$ROOT/kpm/r0lab_raw_compat.c" \
  "$ROOT/kpm/r0lab_raw.h" >/dev/null; then
  fail 'r0lab KPM contains a disabled raw-xom execution path'
fi

if grep -F 'do_mprotect_pkey' "$ROOT/kpm/r0lab.c" >/dev/null; then
  fail 'r0lab KPM still depends on worker-side mprotect(+X)'
fi

require_text kpm/r0lab.c 'struct r0lab_page_record'
require_text kpm/r0lab.c 'record_backend=%s'
require_text kpm/r0lab.c 'R0LAB_PAGE_RECORD_M4_VISIBLE_CLONE'
require_text kpm/r0lab.c 'R0LAB_PAGE_RECORD_RAW_TWO_PFN'
require_text kpm/r0lab.c '#define R0LAB_RAW_PAGE_SLOT_CAPACITY 2U'
require_text kpm/r0lab.c 'struct r0lab_raw_page_table'
require_text kpm/r0lab.c 'r0lab_raw_page_slot_reset_locked'
require_text kpm/r0lab.c 'r0lab_raw_selected_page_locked'
require_text kpm/r0lab.c 'r0lab_raw_page_table_active_count_locked'
require_text kpm/r0lab.c 'r0lab_raw_slot_arm'
require_text kpm/r0lab.c 'raw slot arm '
require_text kpm/r0lab.c 'raw_slot_ready slot=%u'
require_text kpm/r0lab.c 'raw_slot_observed slot=%u'
require_text kpm/r0lab.c 'raw_slot_inspect slot=%u'
require_text kpm/r0lab.c 'raw_slot_patch_check_ok slot=%u'
require_text kpm/r0lab.c 'r0lab_raw_abort_hook_users_locked'
require_text kpm/r0lab.c 'raw_page_table_slots=%u raw_page_table_active=%u raw_selected_slot=%u'
require_text kpm/r0lab.c 'raw_slot_backend=%s raw_slot_state=%s raw_slot_source=%llx raw_slot_source_pfn=%llx raw_slot_shadow_pfn=%llx'
require_text kpm/r0lab.c 's4_abi ready=%s'
require_text kpm/r0lab.c 'g_s4_brk_handler'
require_text kpm/r0lab.c 'g_s4_user_enable_single_step'
require_text kpm/r0lab.c 'R0LAB_EVENT_S4_BRK_OBSERVED'
require_text kpm/r0lab.c 'R0LAB_S4_HOOKED'
require_text kpm/r0lab.c 'next_state=%s'
require_text kpm/r0lab.c 's4_brk_ready target=%llx state=%s mode=brk_only skip_origin=0 single_step=0 pte_switch=0'
require_text kpm/r0lab.c 's4_step_ready target=%llx state=%s mode=step_only brk_skip_origin=1 step_skip_origin=1 single_step=1 pte_switch=0'
require_text kpm/r0lab.c 's4_step_observed target=%llx brk_events=%u step_events=%u enable_events=%u disable_events=%u state=%s mode=step_only brk_skip_origin=1 step_skip_origin=1 single_step=1 pte_switch=0'
require_text kpm/r0lab.c 's4_raw_step_ready target=%llx state=%s mode=raw_step brk_skip_origin=1 step_skip_origin=1 single_step=1 pte_switch=1 raw_state=shadow_active'
require_text kpm/r0lab.c 'pte_begin_events=%u pte_finish_events=%u state=%s mode=raw_step'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_begin_stepping(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_finish_stepping(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_begin_read_cycle(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_finish_read_cycle(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_begin_gup_hide(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_finish_gup_hide(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_begin_fork_hide(struct r0lab_raw_page *page, void *oldmm)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_finish_fork_hide(struct r0lab_raw_page *page, void *oldmm)'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_vma_matches(const struct r0lab_raw_page *page, void *vma_ptr,'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_arm_source_uxn_only(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'vma->vm_mm == (struct mm_struct *)page->mm'
require_text kpm/r0lab.c 'g_m3_page.raw.mm = mm'
require_text kpm/r0lab.c 'r0lab_raw_arm_source_uxn_only(&page->raw)'
require_function_text kpm/r0lab.c r0lab_m3_clear_worker \
  'result = page->raw.state == R0LAB_RAW_RESTORED ?'
require_text kpm/r0lab.c 'r0lab_raw_restore_original(&page->raw)'
require_text kpm/r0lab.c 'source_transition=pte_uxn pte_switch=1'
require_text kpm/r0lab_raw.h 'int r0lab_raw_vma_matches(const struct r0lab_raw_page *page, void *vma,'
require_text kpm/r0lab_raw_compat.c 'page->gup_saved_pte = page->shadow_rx_pte'
require_text kpm/r0lab_raw_compat.c 'page->fork_saved_pte = page->shadow_rx_pte'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_GUP_BEGIN'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_GUP_FINISH'
require_text kpm/r0lab.c 'raw_gup_%s result=%d state=%lu active_kind=%s gup_hide_active=%lu gup_begin_events=%lu gup_finish_events=%lu gup_hide_primitive=proven'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_READ_CYCLE_BEGIN'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_READ_CYCLE_FINISH'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_SYSCALL_READ_CYCLE_BEGIN'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_PRCTL_TRIGGER'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_PRCTL_PATCH'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_PRCTL_RELEASE'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_ABORT_PROBE_HIT'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_ABORT_WRITE_RELEASE'
require_text kpm/r0lab.c 'R0LAB_EVENT_S4_REG_WRITE'
require_text kpm/r0lab.c 'R0LAB_ABORT_PROBE_SOURCE_WRITE_PERMISSION'
require_text kpm/r0lab.c 'raw_read_cycle_begin result=%d state=%lu active_kind=%s read_cycle_active=%lu read_cycle_begin_events=%lu read_cycle_finish_events=%lu read_cycle=uxn_original_exec_resume trigger=supercall pte_switch=1 data_fault=absent exec_resume=pending'
require_text kpm/r0lab.c 'raw_read_cycle_status state=%lu active_kind=%s read_cycle_active=%lu read_cycle_begin_events=%lu read_cycle_finish_events=%lu read_cycle=uxn_original_exec_resume trigger=supercall pte_switch=%u data_fault=absent exec_resume=%s'
require_text kpm/r0lab.c 'raw_syscall_read_cycle_hook_ready symbol=getpid installed=1 target_mm_scoped=1 trigger=syscall_getpid read_cycle=uxn_original_exec_resume observe_only=0 pte_switch=1 data_fault=absent exec_resume=pending'
require_text kpm/r0lab.c 'raw_syscall_hook_status symbol=%s installed=%u hit_events=%u read_cycle_events=%u failures=%u target_mm_scoped=1 trigger=syscall_getpid read_cycle=uxn_original_exec_resume observe_only=0 pte_switch=1 data_fault=absent exec_resume=%s'
require_text kpm/r0lab.c 'r0lab_raw_syscall_hook_users_locked'
require_text kpm/r0lab.c 'raw_slot_syscall_read_cycle_hook_ready slot=%u generation=%llu symbol=getpid installed=1 selected=1 target_mm_scoped=1 page_record_routed=1'
require_text kpm/r0lab.c 'raw_slot_syscall_read_cycle_hook_selected slot=%u generation=%llu symbol=getpid selected=1 target_mm_scoped=1 page_record_routed=1'
require_text kpm/r0lab.c 'raw_slot_syscall_hook_status slot=%u generation=%llu symbol=%s installed=%u selected=%u hit_events=%u read_cycle_events=%u failures=%u target_mm_scoped=1 page_record_routed=1'
require_text kpm/r0lab.c 'raw_slot_syscall_hook_cleared slot=%u generation=%llu symbol=%s installed=0 hit_events=%u read_cycle_events=%u read_cycle_finish_events=%lu failures=%u page_record_routed=1'
require_text kpm/r0lab.c 'r0lab_raw_selected_page_locked()'
require_text kpm/r0lab.c '#define R0LAB_PRCTL_MAGIC 0x52304c42U'
require_text kpm/r0lab.c '#define R0LAB_PRCTL_OP_READ_CYCLE 1U'
require_text kpm/r0lab.c '#define R0LAB_PRCTL_OP_PATCH_WORD 2U'
require_text kpm/r0lab.c '#define R0LAB_PRCTL_OP_RELEASE_PATCH 3U'
require_text kpm/r0lab.c '#define R0LAB_PRCTL_OP_PATCH_RANGE 4U'
require_text kpm/r0lab.c '#define R0LAB_PRCTL_OP_RELEASE_RANGE 5U'
require_text kpm/r0lab.c '#define R0LAB_PATCH_RECORD_CAPACITY 1024U'
require_text kpm/r0lab.c 'g_sys_prctl = r0lab_lookup_first("__arm64_sys_prctl.cfi_jt"'
require_text kpm/r0lab.c 'r0lab_lookup_first("copy_from_user_nofault.cfi_jt",'
require_text kpm/r0lab.c 'g_sync_icache_aliases = (r0lab_sync_icache_aliases_fn_t)'
require_text kpm/r0lab.c 'r0lab_lookup_first("sync_icache_aliases.cfi_jt",'
require_text kpm/r0lab.c '(uint32_t)syscall_regs->regs[0] != R0LAB_PRCTL_MAGIC'
require_text kpm/r0lab.c 'session_valid = current_uid() == g_session.lab_uid && g_session.active &&'
require_text kpm/r0lab.c 'token == g_session.token'
require_text kpm/r0lab.c 'operation == R0LAB_PRCTL_OP_PATCH_WORD'
require_text kpm/r0lab.c 'operation == R0LAB_PRCTL_OP_RELEASE_PATCH'
require_text kpm/r0lab.c 'operation == R0LAB_PRCTL_OP_PATCH_RANGE'
require_text kpm/r0lab.c 'operation == R0LAB_PRCTL_OP_RELEASE_RANGE'
require_text kpm/r0lab.c 'uint16_t patch_rebuild_order[R0LAB_PATCH_RECORD_CAPACITY];'
require_function_text kpm/r0lab.c r0lab_raw_rebuild_patch_range \
  'order = page->patch_rebuild_order;'
require_function_text kpm/r0lab.c r0lab_raw_rebuild_patch_range \
  'g_sync_icache_aliases((unsigned long)page->raw.shadow_kaddr + offset,'
require_function_text kpm/r0lab.c r0lab_raw_rebuild_patch_range \
  'page->patch_records[order[index]]'
require_function_text kpm/r0lab.c r0lab_raw_upsert_patch_locked \
  'page->patch_records[*record_index].version = page->patch_version;'
require_function_text kpm/r0lab.c r0lab_raw_release_patch_locked \
  'record->data = NULL;'
require_function_text kpm/r0lab.c r0lab_raw_detach_one_patch_buffer_locked \
  'record->data = NULL;'
require_function_text kpm/r0lab.c r0lab_raw_drain_patch_buffers_page \
  'buffer = r0lab_raw_detach_one_patch_buffer_locked(page);'
require_text kpm/r0lab.c 'raw slot patch byte '
require_text kpm/r0lab.c 'raw slot patch word '
require_text kpm/r0lab.c 'raw slot patch release '
require_text kpm/r0lab.c 'raw slot patch status '
require_function_text kpm/r0lab.c r0lab_raw_slot_patch_admit_locked \
  'page->transitioning = true;'
require_function_text kpm/r0lab.c r0lab_raw_slot_patch_apply \
  'r0lab_raw_upsert_patch_locked('
require_function_text kpm/r0lab.c r0lab_raw_slot_patch_apply \
  'r0lab_raw_rebuild_patch_range(page, range_offset,'
require_function_text kpm/r0lab.c r0lab_raw_slot_patch_release \
  'r0lab_raw_release_patch_locked('
require_text kpm/r0lab.c 'raw_slot_patch_status slot=%u page=%llx generation=%llu state=%lu patch_record_slots=%u patch_active_count=%u patch_dirty_bytes=%u patch_version=%llu patch_capacity=%u patch_scope=page_slot_ranges'
require_text kpm/r0lab.c 'raw_slot_patch_ok slot=%u generation=%llu offset=%llu length=%u address=%llx patch_record_slots=%u patch_active_count=%u patch_dirty_bytes=%u patch_version=%llu patch_capacity=%u patch_scope=page_slot_ranges'
require_text kpm/r0lab.c 'raw_slot_patch_release_ok slot=%u generation=%llu offset=%llu address=%llx patch_record_slots=%u patch_active_count=%u patch_dirty_bytes=%u patch_version=%llu patch_capacity=%u patch_scope=page_slot_ranges'
require_function_text kpm/r0lab.c r0lab_raw_prctl_before \
  '++g_raw_inflight;'
require_function_text kpm/r0lab.c r0lab_raw_prctl_before \
  'goto out;'
require_function_text kpm/r0lab.c r0lab_raw_prctl_before \
  '--g_raw_inflight;'
require_text kpm/r0lab.c 'raw_prctl_hook_ready symbol=prctl installed=1 abi=prctl_magic'
require_text kpm/r0lab.c 'operations=%u,%u,%u,%u,%u read_cycle_op=%u patch_word_op=%u release_patch_op=%u patch_range_op=%u release_range_op=%u'
require_text kpm/r0lab.c 'patch_scope=single_page_ranges patch_capacity=%u overlap=version_last_write_wins'
require_text kpm/r0lab.c 'passthrough=nonmagic'
require_text kpm/r0lab.c 'raw_va_prot_none'
require_text kpm/r0lab.c 'raw_va_rx_write'
require_text kpm/r0lab.c 'raw_abort_probe_ready symbol=do_mem_abort installed=1 armed=1 target_mm_scoped=1 source=%s observe_only=1 pte_switch=0 data_fault=sync_el0_dabt read_cycle=absent'
require_text kpm/r0lab.c 'raw_slot_abort_probe_ready slot=%u generation=%llu symbol=do_mem_abort installed=1 armed=1 target_mm_scoped=1 page_record_routed=1 source=%s observe_only=1 pte_switch=0 data_fault=sync_el0_dabt read_cycle=absent'
require_text kpm/r0lab.c 'raw_abort_probe_status symbol=%s installed=%u armed=%u read_events=%u write_events=%u exec_events=%u hit_events=%u failures=%u last_far=%llx last_esr=%x last_ec=%u last_fsc_type=%x last_wnr=%u permission_fault=%u translation_fault=%u target_mm_scoped=1 source=%s observe_only=1 pte_switch=0 data_fault=sync_el0_dabt read_cycle=absent'
require_text kpm/r0lab.c 'raw_slot_abort_probe_status slot=%u generation=%llu symbol=%s installed=%u armed=%u read_events=%u write_events=%u exec_events=%u hit_events=%u failures=%u last_far=%llx last_esr=%x last_ec=%u last_fsc_type=%x last_wnr=%u permission_fault=%u translation_fault=%u target_mm_scoped=1 page_record_routed=1 source=%s observe_only=1 pte_switch=0 data_fault=sync_el0_dabt read_cycle=absent'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_ABORT_READ_CYCLE_BEGIN'
require_function_text kpm/r0lab.c r0lab_raw_before_abort \
  'r0lab_raw_hook_page_token_acquire_locked'
require_function_text kpm/r0lab.c r0lab_raw_before_abort \
  'r0lab_raw_begin_fault_read_cycle(&abort_page->raw);'
require_function_text kpm/r0lab.c r0lab_raw_before_abort \
  'r0lab_raw_restore_original(&abort_page->raw);'
require_function_text kpm/r0lab_raw_compat.c r0lab_raw_begin_fault_read_cycle \
  'pte_pfn(current_pte) != page->shadow_pfn'
require_function_text kpm/r0lab_raw_compat.c r0lab_raw_begin_fault_read_cycle \
  'page->state = R0LAB_RAW_ORIGINAL_READ;'
require_text kpm/r0lab.c 'raw_abort_read_cycle_ready symbol=do_mem_abort installed=1 armed=1 target_mm_scoped=1 source=raw_va_prot_none action=begin_read_cycle observe_only=0 pte_switch=1 data_fault=sync_el0_dabt read_cycle=uxn_original_exec_resume skip_origin=1 exec_resume=pending'
require_text kpm/r0lab.c 'raw_slot_abort_read_cycle_ready slot=%u generation=%llu symbol=do_mem_abort installed=1 armed=1 target_mm_scoped=1 page_record_routed=1 source=raw_va_prot_none action=begin_read_cycle observe_only=0 pte_switch=1 data_fault=sync_el0_dabt read_cycle=uxn_original_exec_resume skip_origin=1 exec_resume=pending'
require_text kpm/r0lab.c 'raw_abort_read_cycle_status symbol=%s installed=%u armed=%u read_events=%u failures=%u last_far=%llx last_esr=%x last_ec=%u last_fsc_type=%x last_wnr=%u permission_fault=%u translation_fault=%u begin_result=%d target_mm_scoped=1 source=raw_va_prot_none action=begin_read_cycle observe_only=0 pte_switch=%u data_fault=sync_el0_dabt read_cycle=uxn_original_exec_resume read_cycle_active=%lu read_cycle_begin_events=%lu read_cycle_finish_events=%lu skip_origin=1 exec_resume=%s'
require_text kpm/r0lab.c 'raw_slot_abort_read_cycle_status slot=%u generation=%llu symbol=%s installed=%u armed=%u read_events=%u failures=%u last_far=%llx last_esr=%x last_ec=%u last_fsc_type=%x last_wnr=%u permission_fault=%u translation_fault=%u begin_result=%d target_mm_scoped=1 page_record_routed=1 source=raw_va_prot_none action=begin_read_cycle observe_only=0 pte_switch=%u data_fault=sync_el0_dabt read_cycle=uxn_original_exec_resume read_cycle_active=%lu read_cycle_begin_events=%lu read_cycle_finish_events=%lu skip_origin=1 exec_resume=%s'
require_text kpm/r0lab.c 'raw abort read cycle arm '
require_text kpm/r0lab.c 'raw abort read cycle status '
require_text kpm/r0lab.c 'raw abort read cycle clear '
require_text kpm/r0lab.c 'raw slot abort read cycle arm '
require_text kpm/r0lab.c 'raw slot abort read cycle status '
require_text kpm/r0lab.c 'raw slot abort read cycle clear '
require_text kpm/r0lab.c 'raw abort write probe arm '
require_text kpm/r0lab.c 'raw abort write probe status '
require_text kpm/r0lab.c 'raw abort write probe clear '
require_text kpm/r0lab.c 'raw slot abort write probe arm '
require_text kpm/r0lab.c 'raw slot abort write probe status '
require_text kpm/r0lab.c 'raw slot abort write probe clear '
require_text kpm/r0lab.c 'raw_abort_write_release_ready symbol=do_mem_abort installed=1 armed=1 target_mm_scoped=1 source=raw_va_rx_write action=restore_original logical_release=1 observe_only=0 pte_switch=1 data_fault=sync_el0_dabt read_cycle=absent skip_origin=0'
require_text kpm/r0lab.c 'raw_slot_abort_write_release_ready slot=%u generation=%llu symbol=do_mem_abort installed=1 armed=1 target_mm_scoped=1 page_record_routed=1 source=raw_va_rx_write action=restore_original logical_release=1 observe_only=0 pte_switch=1 data_fault=sync_el0_dabt read_cycle=absent skip_origin=0'
require_text kpm/r0lab.c 'raw_abort_write_release_status symbol=%s installed=%u armed=%u release_events=%u failures=%u last_far=%llx last_esr=%x last_ec=%u last_fsc_type=%x last_wnr=%u permission_fault=%u translation_fault=%u restore_result=%d target_mm_scoped=1 source=raw_va_rx_write action=restore_original logical_release=1 observe_only=0 pte_switch=%u data_fault=sync_el0_dabt read_cycle=absent skip_origin=0'
require_text kpm/r0lab.c 'raw_slot_abort_write_release_status slot=%u generation=%llu symbol=%s installed=%u armed=%u release_events=%u failures=%u last_far=%llx last_esr=%x last_ec=%u last_fsc_type=%x last_wnr=%u permission_fault=%u translation_fault=%u restore_result=%d target_mm_scoped=1 page_record_routed=1 source=raw_va_rx_write action=restore_original logical_release=1 observe_only=0 pte_switch=%u data_fault=sync_el0_dabt read_cycle=absent skip_origin=0'
require_text kpm/r0lab.c 'raw abort write release arm '
require_text kpm/r0lab.c 'raw abort write release status '
require_text kpm/r0lab.c 'raw abort write release clear '
require_text kpm/r0lab.c 'raw slot abort write release arm '
require_text kpm/r0lab.c 'raw slot abort write release status '
require_text kpm/r0lab.c 'raw slot abort write release clear '
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_GUP_HOOK_BEGIN'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_GUP_HOOK_FINISH'
require_text kpm/r0lab.c 'g_follow_page_pte = r0lab_lookup_first("follow_page_pte.cfi_jt"'
require_text kpm/r0lab.c 'hook_wrap5(hook_target, r0lab_raw_gup_pte_before'
require_text kpm/r0lab.c 'hook_wrap4(hook_target, r0lab_raw_gup_mask_before'
require_text kpm/r0lab.c 'r0lab_raw_gup_hook_users_locked'
require_text kpm/r0lab.c 'R0LAB_RAW_HOOK_GUP, vma_mm, address'
require_text kpm/r0lab.c 'local->data2 = slot_id;'
require_text kpm/r0lab.c 'raw slot gup hook arm '
require_text kpm/r0lab.c 'raw slot gup hook status '
require_text kpm/r0lab.c 'raw slot gup hook clear '
require_text kpm/r0lab.c 'raw_gup_hook_ready symbol=%s follow_page_pte=%s follow_page_mask=%s installed=1 mode=%s target_mm_scoped=1 external_reader=1'
require_text kpm/r0lab.c 'raw_gup_hook_status symbol=%s follow_page_pte=%s follow_page_mask=%s installed=%u hook_begin_events=%u hook_finish_events=%u hook_failures=%u primitive_begin_events=%lu primitive_finish_events=%lu target_mm_scoped=1 external_reader=1'
require_text kpm/r0lab.c 'raw_slot_gup_hook_ready slot=%u generation=%llu symbol=%s follow_page_pte=%s follow_page_mask=%s installed=1 mode=%s target_mm_scoped=1 page_record_routed=1 external_reader=1'
require_text kpm/r0lab.c 'raw_slot_gup_hook_status slot=%u generation=%llu symbol=%s follow_page_pte=%s follow_page_mask=%s installed=%u hook_begin_events=%u hook_finish_events=%u hook_failures=%u primitive_begin_events=%lu primitive_finish_events=%lu target_mm_scoped=1 page_record_routed=1 external_reader=1'
require_text kpm/r0lab.c 'raw_slot_gup_hook_cleared slot=%u generation=%llu follow_page_pte=%s follow_page_mask=%s installed=0 hook_begin_events=%u hook_finish_events=%u hook_failures=%u primitive_begin_events=%lu primitive_finish_events=%lu page_record_routed=1'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_FORK_HOOK_BEGIN'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_FORK_HOOK_FINISH'
require_text kpm/r0lab.c 'g_dup_mmap = r0lab_lookup_first("dup_mmap.cfi_jt", "dup_mmap")'
require_text kpm/r0lab.c 'hook_wrap2(g_dup_mmap, r0lab_raw_fork_before'
require_text kpm/r0lab.c 'r0lab_raw_fork_page_eligible_locked'
require_text kpm/r0lab.c 'r0lab_raw_fork_hook_users_locked'
require_text kpm/r0lab.c 'planned_mask |= r0lab_raw_fork_slot_mask'
require_text kpm/r0lab.c 'r0lab_raw_begin_fork_hide(&page->raw, oldmm)'
require_text kpm/r0lab.c 'r0lab_raw_finish_fork_hide(&page->raw, oldmm)'
require_text kpm/r0lab.c 'raw slot fork hook arm '
require_text kpm/r0lab.c 'raw slot fork hook status '
require_text kpm/r0lab.c 'raw slot fork hook clear '
require_text kpm/r0lab.c 'raw_fork_hook_ready symbol=dup_mmap installed=1 parent_pause=1 child_original_inherit=1 target_mm_scoped=1'
require_text kpm/r0lab.c 'raw_slot_fork_hook_ready slot=%u generation=%llu symbol=dup_mmap installed=1 parent_pause=1 child_original_inherit=1 target_mm_scoped=1 page_record_routed=1'
require_text kpm/r0lab.c 'raw_fork_hook_status symbol=%s installed=%u hook_begin_events=%u hook_finish_events=%u hook_failures=%u primitive_begin_events=%lu primitive_finish_events=%lu parent_pause=1 child_original_inherit=1 target_mm_scoped=1'
require_text kpm/r0lab.c 'raw_slot_fork_hook_status slot=%u generation=%llu symbol=%s installed=%u hook_begin_events=%u hook_finish_events=%u hook_failures=%u primitive_begin_events=%lu primitive_finish_events=%lu parent_pause=1 child_original_inherit=1 target_mm_scoped=1 page_record_routed=1'
require_text kpm/r0lab.c 'R0LAB_EVENT_RAW_FAULT_HOOK_HIT'
require_text kpm/r0lab.c 'g_handle_mm_fault = r0lab_lookup_first("handle_mm_fault.cfi_jt"'
require_text kpm/r0lab.c 'hook_wrap4(g_handle_mm_fault, r0lab_raw_fault_before'
require_text kpm/r0lab.c 'raw_fault_hook_ready symbol=handle_mm_fault installed=1 target_mm_scoped=1 observe_only=1 pte_switch=0'
require_text kpm/r0lab.c 'raw_fault_hook_status symbol=%s installed=%u read_events=%u write_events=%u exec_events=%u hit_events=%u failures=%u target_mm_scoped=1 observe_only=1 pte_switch=0'
require_text kpm/r0lab.c 'raw_slot_fault_hook_ready slot=%u generation=%llu symbol=handle_mm_fault installed=1 target_mm_scoped=1 page_record_routed=1 observe_only=1 pte_switch=0'
require_text kpm/r0lab.c 'raw_slot_fault_hook_status slot=%u generation=%llu symbol=%s installed=%u read_events=%u write_events=%u exec_events=%u hit_events=%u failures=%u target_mm_scoped=1 page_record_routed=1 observe_only=1 pte_switch=0'
require_text kpm/r0lab_raw.h 'int r0lab_raw_clear_shadow_access_flag(struct r0lab_raw_page *page);'
require_text kpm/r0lab_raw_compat.c 'int r0lab_raw_clear_shadow_access_flag(struct r0lab_raw_page *page)'
require_text kpm/r0lab_raw_compat.c 'shadow_old = pte_mkold(current_pte);'
require_text kpm/r0lab.c 'raw slot fault af clear '
require_text kpm/r0lab.c 'raw_slot_fault_af_cleared slot=%u generation=%llu page=%llx result=0 pte_af=cleared state=%lu target_mm_scoped=1 page_record_routed=1 pte_switch=0 source=file_backed_rx'
require_text kpm/r0lab.c 'raw slot fault hook arm '
require_text kpm/r0lab.c 'raw slot fault hook status '
require_text kpm/r0lab.c 'raw slot fault hook clear '
require_text kpm/r0lab.c 'raw_fault_probe_ready symbol=handle_mm_fault installed=1 armed=1 page=%llx reader_tgid=0 target_mm_scoped=1 observe_only=1 pte_switch=0 source=normal_anon_remote_gup'
require_text kpm/r0lab.c 'raw_fault_probe_reader_ready reader_tgid=%d armed=1 page=%llx target_mm_scoped=1 remote_only=1 observe_only=1 pte_switch=0 source=normal_anon_remote_gup'
require_text kpm/r0lab.c 'raw_fault_probe_status symbol=%s installed=%u armed=%u page=%llx reader_tgid=%d read_events=%u write_events=%u exec_events=%u hit_events=%u failures=%u target_mm_scoped=1 remote_only=1 observe_only=1 pte_switch=0 source=normal_anon_remote_gup'
require_text kpm/r0lab.c 'fault_hook=observe_only'
require_text kpm/r0lab.c 'hook_wrap3(g_s4_brk_handler, r0lab_s4_brk_before, NULL'
require_text kpm/r0lab.c 'hook_wrap3(g_s4_single_step_handler,'
require_text kpm/r0lab.c 'r0lab_hook_detach(g_s4_brk_handler, r0lab_s4_brk_before, NULL)'
require_text kpm/r0lab.c 'r0lab_hook_detach(g_s4_single_step_handler, r0lab_s4_step_before,'
require_text kpm/r0lab.c 'Step-mode only: consume BRK and run the fixed Lab instruction.'
require_text kpm/r0lab.c 'args->skip_origin = 1'
require_text kpm/r0lab.c 's4_raw_reg_ready target=%llx state=%s mode=raw_reg'
require_text kpm/r0lab.c 'regs->regs[R0LAB_S4_RAW_REG_INDEX] = reg_value'
require_text kpm/r0lab.c 'register_apply=brk_before_single_step'
require_text kpm/r0lab.c 's4 raw-reg arm '
require_text lab-app/src/main/cpp/labprobe.c 'ready=\"%s\" observed=\"%s\"'
require_text lab-app/src/main/cpp/labprobe.c 'R0LAB_S4_CODE_BRK_7'
require_text lab-app/src/main/cpp/labprobe.c 's4 mode=brk-only failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 's4 mode=step-only failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 's4 mode=raw-step failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 's4 mode=raw-reg failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "s4 raw-reg ", 11)'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=gup-hide failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=read-cycle failures=%d trigger=supercall data_fault=absent pte_switch=1 exec_resume=1'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=syscall-read-cycle failures=%d trigger=syscall_getpid read_cycle=uxn_original_exec_resume data_fault=absent pte_switch=1 exec_resume=1'
require_text lab-app/src/main/cpp/labprobe.c 'r0lab_raw_syscall_read_cycle_routing_run'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=syscall-read-cycle-routing failures=%d trigger=syscall_getpid read_cycle=uxn_original_exec_resume route=selected_slot page_record_routed=%d'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw syscall read cycle routing run ", 35)'
require_text lab-app/src/main/cpp/labprobe.c 'r0lab_raw_prctl_hook_routing_run'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=prctl-routing failures=%d trigger=prctl_magic route=selected_slot,address page_record_routed=%d'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw prctl hook routing run ", 27)'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=gup-hook failures=%d reader=external'
require_text lab-app/src/main/cpp/labprobe.c 'r0lab_raw_gup_hook_routing_run'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=gup-hook-routing failures=%d reader=external target_mm_scoped=1 page_record_routed=%d status_source=cross_inspect_clear'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw gup hook routing run ", 25)'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=fork-hook failures=%d parent_pause=1 child_original_inherit=1'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=fault-hook failures=%d observe_only=1 target_mm_scoped=1 pte_switch=0'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=fault-hook-routing fault_route=handle_mm_fault failures=%d route_blocked=prot_none_badaccess_before_handle_mm_fault positive_route=0 page_record_routed=0 target_mm_scoped=1 observe_only=1 pte_switch=0 data_fault_source=raw_va_prot_none'
require_text lab-app/src/main/cpp/labprobe.c 'r0lab_raw_make_file_backed_code_page'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=fault-hook-positive-preflight fault_route=handle_mm_fault failures=%d source=file_backed_rx pte_af_clear=1 positive_route=%d page_record_routed=%d'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw fault hook positive preflight run ", 38)'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=fault-data-probe failures=%d observe_only=1 target_mm_scoped=1 remote_only=1 pte_switch=0 data_fault_source=normal_anon_remote_gup'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=abort-probe failures=%d observe_only=1 target_mm_scoped=1 pte_switch=0 data_fault_source=raw_va_prot_none data_fault=sync_el0_dabt read_cycle=absent'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=abort-read-cycle failures=%d trigger=do_mem_abort target_mm_scoped=1 pte_switch=1 data_fault_source=raw_va_prot_none data_fault=sync_el0_dabt read_cycle=uxn_original_exec_resume skip_origin=1 observe_only=0'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=hook-routing abort_route=read-cycle failures=%d page_record_routed=1 target_mm_scoped=1'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=abort-write-probe failures=%d observe_only=1 target_mm_scoped=1 pte_switch=0 data_fault_source=raw_va_rx_write data_fault=sync_el0_dabt read_cycle=absent'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=abort-write-release failures=%d target_mm_scoped=1 source=raw_va_rx_write action=restore_original logical_release=1 observe_only=0 pte_switch=1 data_fault=sync_el0_dabt read_cycle=absent skip_origin=0'
require_text lab-app/src/main/cpp/labprobe.c 'g_r0lab_raw_signal_jump_on_fault = 1'
require_text lab-app/src/main/cpp/labprobe.c 'siglongjmp(g_r0lab_raw_signal_jump, 1)'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw abort read cycle run ", 25)'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw hook routing run ", 21)'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw fault hook routing run ", 27)'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw abort write probe run ", 26)'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw abort write release run ", 28)'
require_text lab-app/src/main/cpp/labprobe.c 'strcmp(source_permissions, "r-xp")'
require_text lab-app/src/main/cpp/labprobe.c 'strcmp(during_permissions, "r-xp")'
require_text lab-app/src/main/cpp/labprobe.c '__NR_process_vm_readv'
require_text lab-app/src/main/cpp/labprobe.c 'child = fork()'
require_text lab-app/src/main/cpp/labprobe.c 'local_result.word = ((volatile uint32_t *)page)[0]'
require_text lab-app/src/main/cpp/labprobe.c 'parent_pid, &local_iov, 1'
require_text lab-app/src/main/cpp/labprobe.c 'raw fault probe reader 0x%llx %d'
require_text lab-app/src/main/cpp/labprobe.c 'r0lab_wait_for_reply("m4 ready"'
require_text lab-app/src/main/cpp/labprobe.c 'snprintf(observed_reply'
require_text lab-app/src/main/cpp/labprobe.c 'm5 mode=raw-hold'
require_text scripts/test_s4_brk_device.sh 's4 mode=brk-only failures=0'
require_text scripts/test_s4_brk_device.sh 'op=24 result=0'
require_text scripts/test_s4_brk_device.sh 'op=26 result=0'
require_text scripts/test_s4_step_device.sh 's4 mode=step-only failures=0'
require_text scripts/test_s4_step_device.sh 'op=25 result=0'
require_text scripts/test_s4_raw_step_device.sh 's4 mode=raw-step failures=0'
require_text scripts/test_s4_raw_step_device.sh 'hook_value=99'
require_text scripts/test_s4_raw_step_device.sh 'pte_begin_events=1'
require_text scripts/test_s4_raw_step_device.sh 'pte_finish_events=1'
require_text scripts/test_s4_raw_reg_device.sh 's4 mode=raw-reg failures=0'
require_text scripts/test_s4_raw_reg_device.sh 'hook_value=73'
require_text scripts/test_s4_raw_reg_device.sh 'restored_value=42'
require_text scripts/test_s4_raw_reg_device.sh 'reg_write_events=1'
require_text scripts/test_s4_raw_reg_device.sh 'register_apply=brk_before_single_step'
require_text scripts/test_s4_raw_reg_device.sh 'op=41 result=0'
require_text scripts/test_raw_gup_hide_device.sh 'raw mode=gup-hide failures=0'
require_text scripts/test_raw_gup_hide_device.sh 'original_view_after_shadow=proven'
require_text scripts/test_raw_gup_hide_device.sh 'gup_hide_primitive=proven'
require_text scripts/test_raw_read_cycle_device.sh 'raw mode=read-cycle failures=0'
require_text scripts/test_raw_read_cycle_device.sh 'original_read_word=52800540'
require_text scripts/test_raw_read_cycle_device.sh 'shadow_after_resume=52800c60'
require_text scripts/test_raw_read_cycle_device.sh 'read_cycle=uxn_original_exec_resume'
require_text scripts/test_raw_read_cycle_device.sh 'read_cycle_exec_resume=proven'
require_text scripts/test_raw_read_cycle_device.sh 'read_cycle_data_fault=absent'
require_text scripts/test_raw_read_cycle_device.sh 'op=36 result=0'
require_text scripts/test_raw_read_cycle_device.sh 'op=37 result=0'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'raw mode=syscall-read-cycle failures=0'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'trigger=syscall_getpid'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'read_cycle=uxn_original_exec_resume'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'original_read_word=52800540'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'shadow_after_resume=52800c60'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'read_cycle_events=1'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'op=35 result=0'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'op=38 result=0'
require_text scripts/test_raw_syscall_read_cycle_device.sh 'op=37 result=0'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'raw mode=syscall-read-cycle-routing failures=0'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'route=selected_slot'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'page_record_routed=1'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'stale_generation_rc=-11'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'route_slot0_events=1 route_slot1_events=1'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'status_slot0=1/1/1'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'status_slot1=1/1/1'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'clear_hit=1/1 clear_finish=1/1 clear_failures=0/0'
require_text scripts/test_raw_syscall_hook_routing_device.sh 'raw_syscall_hook_routing=pass'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'raw mode=prctl-dispatch failures=0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'trigger=prctl_magic'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'option=52304c42'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'operations=1,2,3,4,5'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'dispatch=patch_word,release_patch,patch_range,release_range,read_cycle'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'reject_rc=-1'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'reject_errno=1'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'shadow_after_reject=52800c60'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'patch_value=77'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'patch_word=528009a0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'release_value=99'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'released_word=52800c60'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'patch_events=1'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'release_events=1'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'reject_events=1'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'passthrough=nonmagic'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'passthrough_stress_failures=0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'passthrough_thread_rc=0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'passthrough_join_rc=0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'STRESS_ITERATIONS'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=42 result=-1'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=42 result=0.* x0=2 '
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=42 result=0.* x0=3 '
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=42 result=0.* x0=1 '
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=43 result=0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=44 result=0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=38 result=0'
require_text scripts/test_raw_prctl_read_cycle_device.sh 'op=37 result=0'
require_text scripts/test_raw_prctl_patch_records_device.sh 'raw mode=prctl-patch-records failures=0'
require_text scripts/test_raw_prctl_patch_records_device.sh 'patch_capacity=1024'
require_text scripts/test_raw_prctl_patch_records_device.sh 'overlap_after_b=pass'
require_text scripts/test_raw_prctl_patch_records_device.sh 'release_b_rebuild=pass'
require_text scripts/test_raw_prctl_patch_records_device.sh 'shrink_rebuild=pass'
require_text scripts/test_raw_prctl_patch_records_device.sh 'capacity_fill_records=1023'
require_text scripts/test_raw_prctl_patch_records_device.sh 'capacity_overflow_errno=28'
require_text scripts/test_raw_prctl_patch_records_device.sh 'capacity_boundary=pass'
require_text scripts/test_raw_prctl_patch_records_device.sh 'active_progress=1,2,1,1,0,1,1024'
require_text scripts/test_raw_prctl_patch_records_device.sh 'dirty_progress=8,12,8,4,0,4,1027'
require_text scripts/test_raw_prctl_patch_records_device.sh 'op=45 result=-28'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'raw prctl hook routing run'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'raw mode=prctl-routing failures=0'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'route=selected_slot,address'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'page_record_routed=1'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'stale_generation_rc=-11'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'read_status=1/1'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'patch_isolation=1'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'release_isolation=1'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'capacity_fill_records=1023'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'capacity_boundary=pass'
require_text scripts/test_raw_prctl_hook_routing_device.sh 'raw_prctl_hook_routing=pass'
require_text lab-app/src/main/cpp/labprobe.c '#include <stdatomic.h>'
require_function_text lab-app/src/main/cpp/labprobe.c \
  r0lab_prctl_passthrough_stress_thread \
  'atomic_load_explicit(&stress->stop, memory_order_relaxed)'
require_function_text lab-app/src/main/cpp/labprobe.c \
  r0lab_prctl_passthrough_stress_thread \
  'atomic_fetch_add_explicit(&stress->iterations, 1,'
require_function_text lab-app/src/main/cpp/labprobe.c \
  r0lab_raw_prctl_read_cycle_run \
  'atomic_store_explicit(&passthrough_stress.stop, true,'
require_text scripts/test_raw_gup_hook_device.sh 'raw mode=gup-hook failures=0'
require_text scripts/test_raw_gup_hook_device.sh 'reader=external'
require_text scripts/test_raw_gup_hook_device.sh 'gup_read_word=52800540'
require_text scripts/test_raw_gup_hook_device.sh 'target_mm_scoped=1'
require_text scripts/test_raw_gup_hook_device.sh 'external_reader=1'
require_text scripts/test_raw_gup_hook_device.sh 'child_exit=0'
require_text scripts/test_raw_gup_hook_device.sh 'hook_begin_events=1'
require_text scripts/test_raw_gup_hook_device.sh 'hook_finish_events=1'
require_text scripts/test_raw_gup_hook_device.sh 'op=29 result=0'
require_text scripts/test_raw_gup_hook_device.sh 'op=30 result=0'
require_text scripts/test_raw_gup_hook_routing_device.sh 'raw gup hook routing run'
require_text scripts/test_raw_gup_hook_routing_device.sh 'raw mode=gup-hook-routing failures=0'
require_text scripts/test_raw_gup_hook_routing_device.sh 'page_record_routed=1'
require_text scripts/test_raw_gup_hook_routing_device.sh 'status_source=cross_inspect_clear'
require_text scripts/test_raw_gup_hook_routing_device.sh 'primitive_begin_events=1'
require_text scripts/test_raw_gup_hook_routing_device.sh 'primitive_finish_events=1'
require_text scripts/test_raw_gup_hook_routing_device.sh 'op=29 result=0'
require_text scripts/test_raw_gup_hook_routing_device.sh 'op=30 result=0'
require_text scripts/test_raw_gup_hook_routing_device.sh 'expected two raw gup hook begin events'
require_text scripts/test_raw_gup_hook_routing_device.sh 'raw_gup_hook_routing=pass'
require_text scripts/test_raw_fork_hook_device.sh 'raw mode=fork-hook failures=0'
require_text scripts/test_raw_fork_hook_device.sh 'parent_pause=1'
require_text scripts/test_raw_fork_hook_device.sh 'child_original_inherit=1'
require_text scripts/test_raw_fork_hook_device.sh 'child_word=52800540'
require_text scripts/test_raw_fork_hook_device.sh 'child_value=42'
require_text scripts/test_raw_fork_hook_device.sh 'fork_hide_primitive=proven'
require_text scripts/test_raw_fork_hook_device.sh 'op=31 result=0'
require_text scripts/test_raw_fork_hook_device.sh 'op=32 result=0'
require_text lab-app/src/main/cpp/labprobe.c 'slot_hook_status_rc'
require_text lab-app/src/main/cpp/labprobe.c 'raw slot fork hook status 0x%llx 0'
require_text lab-app/src/main/cpp/labprobe.c 'r0lab_control_raw_retry_once'
require_text lab-app/src/main/cpp/labprobe.c 'status_first_rc=%ld/%ld'
require_text scripts/test_raw_fork_hook_routing_device.sh 'raw fork hook routing run'
require_text scripts/test_raw_fork_hook_routing_device.sh 'raw mode=fork-hook-routing failures=0'
require_text scripts/test_raw_fork_hook_routing_device.sh 'page_record_routed=1'
require_text scripts/test_raw_fork_hook_routing_device.sh 'status_source=cross_clear'
require_text scripts/test_raw_fork_hook_routing_device.sh 'child_word=52800540/52800540'
require_text scripts/test_raw_fork_hook_routing_device.sh 'after_fork_shadow=52800c60/52800c60'
require_text scripts/test_raw_fork_hook_routing_device.sh 'raw_slot_fork_hook_ready slot=0'
require_text scripts/test_raw_fork_hook_routing_device.sh 'raw_slot_fork_hook_ready slot=1'
require_text lab-app/src/main/cpp/labprobe.c 'status_source=cross_clear'
require_text lab-app/src/main/cpp/labprobe.c 'raw_slot_fork_hook_cleared slot=0'
require_text lab-app/src/main/cpp/labprobe.c 'raw_slot_fork_hook_cleared slot=1'
require_text scripts/test_raw_fork_hook_routing_device.sh 'expected two raw fork hook begin events'
require_text scripts/test_raw_fork_hook_routing_device.sh 'expected two raw fork hook finish events'
require_text scripts/test_raw_fork_hook_routing_device.sh 'raw_fork_hook_routing=pass'
require_text scripts/test_raw_fault_hook_device.sh 'raw mode=fault-hook failures=0'
require_text scripts/test_raw_fault_hook_device.sh 'observe_only=1'
require_text scripts/test_raw_fault_hook_device.sh 'target_mm_scoped=1'
require_text scripts/test_raw_fault_hook_device.sh 'pte_switch=0'
require_text scripts/test_raw_fault_hook_device.sh 'op=33 result=0'
require_text scripts/test_raw_fault_hook_routing_device.sh 'raw mode=fault-hook-routing'
require_text scripts/test_raw_fault_hook_routing_device.sh 'fault_route=handle_mm_fault'
require_text scripts/test_raw_fault_hook_routing_device.sh 'route_blocked=prot_none_badaccess_before_handle_mm_fault'
require_text scripts/test_raw_fault_hook_routing_device.sh 'positive_route=0'
require_text scripts/test_raw_fault_hook_routing_device.sh 'page_record_routed=0'
require_text scripts/test_raw_fault_hook_routing_device.sh 'data_fault_source=raw_va_prot_none'
require_text scripts/test_raw_fault_hook_routing_device.sh 'handler_faults=2'
require_text scripts/test_raw_fault_hook_routing_device.sh 'expected zero raw fault hook hit events for blocked diagnostic'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'raw fault hook positive preflight run'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'source=file_backed_rx'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'pte_af_clear=1'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'positive_route=1'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'classification=handle_mm_fault_positive_blocked'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'expected zero raw fault hook hit events for blocked preflight'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'op=33 result=0'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'expected two raw fault hook hit events'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'raw_fault_hook_positive_preflight=pass'
require_text scripts/test_raw_fault_hook_positive_preflight_device.sh 'raw_fault_hook_positive_preflight=blocked'
require_text scripts/test_raw_fault_data_probe_device.sh 'raw mode=fault-data-probe failures=0'
require_text scripts/test_raw_fault_data_probe_device.sh 'data_fault_source=normal_anon_remote_gup'
require_text scripts/test_raw_fault_data_probe_device.sh 'raw_fault_probe_reader_ready'
require_text scripts/test_raw_fault_data_probe_device.sh 'target_mm_scoped=1'
require_text scripts/test_raw_fault_data_probe_device.sh 'remote_only=1'
require_text scripts/test_raw_fault_data_probe_device.sh 'fault_probe_read_events=1'
require_text scripts/test_raw_fault_data_probe_device.sh 'op=33 result=0'
require_text scripts/test_raw_abort_probe_device.sh 'raw mode=abort-probe failures=0'
require_text scripts/test_raw_abort_probe_device.sh 'data_fault_source=raw_va_prot_none'
require_text scripts/test_raw_abort_probe_device.sh 'data_fault=sync_el0_dabt'
require_text scripts/test_raw_abort_probe_device.sh 'handler_faults=1'
require_text scripts/test_raw_abort_probe_device.sh 'permission_fault=0'
require_text scripts/test_raw_abort_probe_device.sh 'translation_fault=1'
require_text scripts/test_raw_abort_probe_device.sh 'op=39 result=0'
require_text scripts/test_raw_abort_write_probe_device.sh 'raw mode=abort-write-probe failures=0'
require_text scripts/test_raw_abort_write_probe_device.sh 'data_fault_source=raw_va_rx_write'
require_text scripts/test_raw_abort_write_probe_device.sh 'source=raw_va_rx_write'
require_text scripts/test_raw_abort_write_probe_device.sh 'probe_write_fault_caught=1'
require_text scripts/test_raw_abort_write_probe_device.sh 'handler_faults=1'
require_text scripts/test_raw_abort_write_probe_device.sh 'last_fsc_type=c'
require_text scripts/test_raw_abort_write_probe_device.sh 'last_wnr=1'
require_text scripts/test_raw_abort_write_probe_device.sh 'permission_fault=1'
require_text scripts/test_raw_abort_write_probe_device.sh 'translation_fault=0'
require_text scripts/test_raw_abort_write_probe_device.sh 'op=39 result=0'
require_text scripts/test_raw_abort_write_probe_device.sh 'op=22 result=0'
require_text scripts/test_raw_abort_write_release_device.sh 'raw mode=abort-write-release failures=0'
require_text scripts/test_raw_abort_write_release_device.sh 'action=restore_original'
require_text scripts/test_raw_abort_write_release_device.sh 'logical_release=1'
require_text scripts/test_raw_abort_write_release_device.sh 'observe_only=0'
require_text scripts/test_raw_abort_write_release_device.sh 'pte_switch=1'
require_text scripts/test_raw_abort_write_release_device.sh 'skip_origin=0'
require_text scripts/test_raw_abort_write_release_device.sh 'post_release_exec_value=42'
require_text scripts/test_raw_abort_write_release_device.sh 'active_kind=original'
require_text scripts/test_raw_abort_write_release_device.sh 'release_events=1'
require_text scripts/test_raw_abort_write_release_device.sh 'restore_result=0'
require_text scripts/test_raw_abort_write_release_device.sh 'op=40 result=0'
require_text scripts/test_raw_abort_write_release_device.sh 'op=22 result=0'
require_text scripts/test_raw_hook_routing_device.sh 'raw mode=hook-routing'
require_text scripts/test_raw_hook_routing_device.sh 'abort_route=read-cycle'
require_text scripts/test_raw_hook_routing_device.sh 'page_record_routed=1'
require_text scripts/test_raw_hook_routing_device.sh 'raw_slot_abort_read_cycle_ready slot=0'
require_text scripts/test_raw_hook_routing_device.sh 'raw_slot_abort_read_cycle_ready slot=1'
require_text scripts/test_raw_hook_routing_device.sh 'op=47 result=0'
require_text scripts/test_raw_hook_routing_device.sh 'raw_hook_routing=pass abort_route=read-cycle'
require_text kpm/r0lab.c 'hook_unwrap_remove(func, before, after, 0);'
require_text references/KernelPatch/kernel/include/hook.h '#define HOOK_CHAIN_NUM 0x400'
require_text references/KernelPatch/kernel/include/hook.h '#define FP_HOOK_CHAIN_NUM 0x400'
if grep -F 'hook_unwrap(' kpm/r0lab.c >/dev/null; then
  printf '%s\n' 'unexpected unsafe hook_unwrap() call in kpm/r0lab.c' >&2
  exit 1
fi
require_text scripts/test_raw_exit_hook_device.sh 'raw mode=exit-hook-hold failures=0'
require_text scripts/test_raw_exit_hook_device.sh 'symbol=exit_mmap'
require_text scripts/test_raw_exit_hook_device.sh 'exit_hook_installed=1'
require_text scripts/test_raw_exit_hook_device.sh 'op=34 result=0'
require_text scripts/test_raw_exit_hook_device.sh 'op=22 result=0'
require_text scripts/test_v1_device.sh 'run_phase s4_step scripts/test_s4_step_device.sh'
require_text scripts/test_v1_device.sh 'run_phase s4_raw_step scripts/test_s4_raw_step_device.sh'
require_text scripts/test_v1_device.sh 'run_phase s4_raw_reg scripts/test_s4_raw_reg_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_page_table scripts/test_raw_page_table_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_read_cycle scripts/test_raw_read_cycle_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_syscall_read_cycle scripts/test_raw_syscall_read_cycle_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_prctl_read_cycle scripts/test_raw_prctl_read_cycle_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_prctl_patch_records scripts/test_raw_prctl_patch_records_device.sh'
require_text scripts/test_v1_device.sh 'adb_device shell am force-stop "$LAB_PACKAGE"'
require_text scripts/test_v1_device.sh 'run_phase raw_gup_hide scripts/test_raw_gup_hide_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_gup_hook scripts/test_raw_gup_hook_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_fork_hook scripts/test_raw_fork_hook_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_fault_hook scripts/test_raw_fault_hook_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_fault_data_probe scripts/test_raw_fault_data_probe_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_abort_probe scripts/test_raw_abort_probe_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_abort_write_probe scripts/test_raw_abort_write_probe_device.sh'
require_text scripts/test_v1_device.sh 'run_phase raw_abort_write_release scripts/test_raw_abort_write_release_device.sh'
require_text scripts/test_m5_lifecycle_device.sh 'm5_target_exit_phases=m3,m4,raw,s4'
require_text scripts/test_m5_lifecycle_device.sh "run_phase raw \"\$RAW_TOKEN\" 'm5 raw-hold' 'raw-hold' 'raw_slots' 22"
require_text scripts/test_m5_lifecycle_device.sh "run_phase s4 \"\$S4_TOKEN\" 'm5 s4-hold' 's4-hold' 's4_slots' 26"
require_text scripts/test_m5_lifecycle_device.sh "run_dual_phase s4_raw_step \"\$S4_RAW_STEP_TOKEN\" 'm5 s4-raw-step-hold'"
require_text scripts/test_m3_device.sh 'op=14 result=0'
require_text scripts/test_m4_device.sh 'record_backend=visible_clone record_state=source_uxn'
require_text scripts/test_m4_device.sh 'source_perms=r-xp/r-xp/r-xp clone_perms=r-xp/r-xp/r-xp'
require_text lab-app/src/main/cpp/labprobe.c 'm5 mode=s4-hold failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 'm5 mode=s4-raw-step-hold failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=page-table failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw page table run ", 19)'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=exit-hook-hold failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw exit hook hold ", 19)'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "m5 s4-raw-step-hold ", 20)'
require_text kpm/r0lab.c 'r0lab_s4_monitor_worker'
require_text kpm/r0lab.c 'r0lab_session_has_slots_locked'
require_text kpm/r0lab.c 'r0lab_session_monitor_loop'
require_text kpm/r0lab.c 'r0lab_raw_exit_mmap_before'
require_text kpm/r0lab.c 'page->clearing && !page->target_exiting'
require_text kpm/r0lab.c 'exit_hook=exit_mmap_observe'

require_text scripts/test_raw_abort_read_cycle_device.sh 'raw mode=abort-read-cycle failures=0'
require_text scripts/test_raw_abort_read_cycle_device.sh 'op=47 result=0'
require_text scripts/test_v1_device.sh 'run_phase raw_abort_read_cycle scripts/test_raw_abort_read_cycle_device.sh'
require_text scripts/test_raw_page_table_device.sh 'raw mode=page-table failures=0'
require_text scripts/test_raw_page_table_device.sh 'slot0_activations=1 slot1_activations=1'
require_text scripts/test_raw_page_table_device.sh 'patch_cross_page_rc=-22'
require_text scripts/test_raw_page_table_device.sh 'raw_page_table_activations=2'
require_text scripts/test_raw_page_table_patch_records_device.sh 'raw mode=page-table-patch-records failures=0'
require_text scripts/test_raw_page_table_patch_records_device.sh 'slot0_patch_value=77 slot1_patch_value=88'
require_text scripts/test_raw_page_table_patch_records_device.sh 'after_release0_slot0=99 after_release0_slot1=88'
require_text scripts/test_raw_page_table_patch_records_device.sh 'slot0_patch_record_slots=1024 slot0_patch_active_count=1024'
require_text scripts/test_raw_page_table_patch_records_device.sh 'slot0_capacity_overflow_errno=28'
require_text scripts/test_raw_page_table_patch_records_device.sh 'slot1_patch_record_slots=1 slot1_patch_active_count=1'
require_text scripts/test_raw_page_table_patch_records_device.sh 'slot1_after_slot0_capacity_value=88'
require_text scripts/test_raw_page_table_patch_records_device.sh 'final_original_slot0=42 final_original_slot1=42'
require_text scripts/test_raw_page_table_patch_records_device.sh 'raw_page_table_patch_records=pass'
require_text scripts/test_v1_device.sh 'run_phase raw_page_table_patch_records scripts/test_raw_page_table_patch_records_device.sh'
require_text lab-app/src/main/cpp/labprobe.c 'raw mode=page-table-patch-records failures=%d'
require_text lab-app/src/main/cpp/labprobe.c 'strncmp(args, "raw page table patch records run ", 33)'

printf '%s\n' 'v1_contract=pass scripts=43 raw_pte_kpm=lab_two_pfn raw_page_table=two_slot_lab_harness raw_page_table_patch_records=page_local_records f3_plan=page_local_patch_records_locked f4_plan=hook_routing_by_page_record_locked f4_helper=route_token_status_ready f4_abort_route=two_slot_read_cycle f4_fault_route=prot_none_blocked_diagnostic f4_fault_positive_plan=file_backed_rx_pte_af_preflight_locked f4_fault_positive_preflight=classified_blocked f4_gup_route=two_slot_external_reader f4_fork_route=two_slot_dup_mmap_parent_page_list f4_syscall_route=selected_slot_generation f4_exit_plan=owner_exit_page_record_routing_locked s4_brk=brk_only s4_step=raw_pte_step s4_reg=fixed_x1_before_step raw_gup_hide=primitive raw_read_cycle=uxn_original_exec_resume raw_syscall_read_cycle=hook_triggered raw_prctl_dispatch=read_patch_release_range_records raw_prctl_patch_records=versioned_overlap_rebuild raw_gup_hook=target_mm_external_reader raw_fork_hook=dup_mmap_parent_pause raw_fault_hook=handle_mm_fault_observe_only raw_fault_data_probe=normal_anon_remote_gup raw_abort_probe=sync_el0_translation_dabt_observe raw_abort_read_cycle=sync_el0_translation_dabt_read_cycle raw_abort_write_probe=sync_el0_permission_dabt_observe raw_abort_write_release=write_fault_restore_original raw_exit_hook=exit_mmap_observe result=pass'
